<?php

/**
 * @file
 * Glazed sub-theme.
 *
 * Place your custom PHP code in this file.
 */

/**
 * Implements hook_preprocess_page().
 */
// phpcs:disable
function glazed_STARTERKIT_preprocess_page(&$variables) {
  $glazed_libraries = [
    // Bootstrap TAILORING.
    'glazed_STARTERKIT/bootstrap-3',
    'glazed_STARTERKIT/bootstrap-theme',
    'glazed_STARTERKIT/jquery-ui',
    // GLAZED BASE.
    'glazed_STARTERKIT/footer-menu',
    'glazed_STARTERKIT/forms',
    'glazed_STARTERKIT/layout',
    'glazed_STARTERKIT/page-title',
    'glazed_STARTERKIT/typography',
    // GLAZED Components.
    'glazed_STARTERKIT/stpe-buttons',
    'glazed_STARTERKIT/glazed-full-screen-search',
    'glazed_STARTERKIT/glazed-header',
    'glazed_STARTERKIT/glazed-header--top',
    'glazed_STARTERKIT/glazed-header--side',
    'glazed_STARTERKIT/glazed-header--mobile',
    'glazed_STARTERKIT/glazed-secondary-header',
    'glazed_STARTERKIT/pager-prevnext',
    'glazed_STARTERKIT/glazed-admin',
    // Overrides.
    'glazed_STARTERKIT/cubeportfolio',
    'glazed_STARTERKIT/drupal-breadcrumbs',
    'glazed_STARTERKIT/drupal-comments',
    'glazed_STARTERKIT/drupal-pager',
    'glazed_STARTERKIT/drupal-webform',
    'glazed_STARTERKIT/cms-bootstrap-core',
    'glazed_STARTERKIT/cms-bootstrap-blog',
    'glazed_STARTERKIT/cms-bootstrap-events',
    'glazed_STARTERKIT/cms-bootstrap-news',
    'glazed_STARTERKIT/cms-bootstrap-portfolio',
    'glazed_STARTERKIT/sooperthemes-premium-elements',
    'glazed_STARTERKIT/glazed-builder',
    // HELPERS.
    'glazed_STARTERKIT/helper-classes',
  ];
  foreach ($glazed_libraries as $glazed_library) {
    $variables['#attached']['library'][] = $glazed_library;
  }
}
// phpcs:enable
