<?php
/**
 * @file
 * glazed_landscaping_theme_settings.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function glazed_landscaping_theme_settings_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: main-menu_about-us:uuid/node/1af1985e-f4ee-4e25-b584-781fcd853332.
  $menu_links['main-menu_about-us:uuid/node/1af1985e-f4ee-4e25-b584-781fcd853332'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/1af1985e-f4ee-4e25-b584-781fcd853332',
    'router_path' => 'uuid',
    'link_title' => 'About Us',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_about-us:uuid/node/1af1985e-f4ee-4e25-b584-781fcd853332',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'uuid' => '1af1985e-f4ee-4e25-b584-781fcd853332',
    'vuuid' => '70c01f39-c118-4e24-ae80-d635823ecd5d',
    'parent_identifier' => 'main-menu_company:uuid/node/1af1985e-f4ee-4e25-b584-781fcd853332',
  );
  // Exported menu link: main-menu_certifications:uuid/node/1abaeec4-5273-4080-a1ec-d253ea9fdad2.
  $menu_links['main-menu_certifications:uuid/node/1abaeec4-5273-4080-a1ec-d253ea9fdad2'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/1abaeec4-5273-4080-a1ec-d253ea9fdad2',
    'router_path' => 'uuid',
    'link_title' => 'Certifications',
    'options' => array(
      'identifier' => 'main-menu_certifications:uuid/node/1abaeec4-5273-4080-a1ec-d253ea9fdad2',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => '1abaeec4-5273-4080-a1ec-d253ea9fdad2',
    'vuuid' => '06521a4e-89bb-4b28-841b-eccd3f9cfef2',
    'parent_identifier' => 'main-menu_company:uuid/node/1af1985e-f4ee-4e25-b584-781fcd853332',
  );
  // Exported menu link: main-menu_company-history:uuid/node/1a2eb42e-f011-44c2-9005-8d3bde5808d6.
  $menu_links['main-menu_company-history:uuid/node/1a2eb42e-f011-44c2-9005-8d3bde5808d6'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/1a2eb42e-f011-44c2-9005-8d3bde5808d6',
    'router_path' => 'uuid',
    'link_title' => 'Company History',
    'options' => array(
      'identifier' => 'main-menu_company-history:uuid/node/1a2eb42e-f011-44c2-9005-8d3bde5808d6',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => '1a2eb42e-f011-44c2-9005-8d3bde5808d6',
    'vuuid' => '6a9b2732-d299-4daf-8404-bc0a6643f2a9',
    'parent_identifier' => 'main-menu_company:uuid/node/1af1985e-f4ee-4e25-b584-781fcd853332',
  );
  // Exported menu link: main-menu_company:uuid/node/1af1985e-f4ee-4e25-b584-781fcd853332.
  $menu_links['main-menu_company:uuid/node/1af1985e-f4ee-4e25-b584-781fcd853332'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/1af1985e-f4ee-4e25-b584-781fcd853332',
    'router_path' => 'uuid',
    'link_title' => 'Company',
    'options' => array(
      'identifier' => 'main-menu_company:uuid/node/1af1985e-f4ee-4e25-b584-781fcd853332',
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -49,
    'customized' => 1,
    'uuid' => '1af1985e-f4ee-4e25-b584-781fcd853332',
    'vuuid' => '70c01f39-c118-4e24-ae80-d635823ecd5d',
  );
  // Exported menu link: main-menu_contact-us:uuid/node/1a3fd21b-06a2-4468-9930-414d071b19ad.
  $menu_links['main-menu_contact-us:uuid/node/1a3fd21b-06a2-4468-9930-414d071b19ad'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/1a3fd21b-06a2-4468-9930-414d071b19ad',
    'router_path' => 'uuid',
    'link_title' => 'Contact Us',
    'options' => array(
      'attributes' => array(),
      'html' => 1,
      'identifier' => 'main-menu_contact-us:uuid/node/1a3fd21b-06a2-4468-9930-414d071b19ad',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'uuid' => '1a3fd21b-06a2-4468-9930-414d071b19ad',
    'vuuid' => '194fc26a-f2d5-473c-bbb6-5aeae11b83e5',
  );
  // Exported menu link: main-menu_faq:uuid/node/1a04f805-c2d2-4511-a841-69494330f8ff.
  $menu_links['main-menu_faq:uuid/node/1a04f805-c2d2-4511-a841-69494330f8ff'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/1a04f805-c2d2-4511-a841-69494330f8ff',
    'router_path' => 'uuid',
    'link_title' => 'FAQ',
    'options' => array(
      'identifier' => 'main-menu_faq:uuid/node/1a04f805-c2d2-4511-a841-69494330f8ff',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => '1a04f805-c2d2-4511-a841-69494330f8ff',
    'vuuid' => 'f360b32e-3ab1-4357-a9d7-7c1ac77a89bb',
    'parent_identifier' => 'main-menu_company:uuid/node/1af1985e-f4ee-4e25-b584-781fcd853332',
  );
  // Exported menu link: main-menu_garden-architecture:uuid/node/1a8ef59e-4e21-4502-8c6e-2deeac705df7.
  $menu_links['main-menu_garden-architecture:uuid/node/1a8ef59e-4e21-4502-8c6e-2deeac705df7'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/1a8ef59e-4e21-4502-8c6e-2deeac705df7',
    'router_path' => 'uuid',
    'link_title' => 'Garden Architecture',
    'options' => array(
      'identifier' => 'main-menu_garden-architecture:uuid/node/1a8ef59e-4e21-4502-8c6e-2deeac705df7',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'uuid' => '1a8ef59e-4e21-4502-8c6e-2deeac705df7',
    'vuuid' => '2fdbdcbd-a1f4-404e-9510-d8399823ec2e',
    'parent_identifier' => 'main-menu_services:uuid/node/1a3bc130-4909-4119-8127-488df7d11c11',
  );
  // Exported menu link: main-menu_home:uuid/node/1aa48b9e-63be-4e62-a816-aa3a95159c8a.
  $menu_links['main-menu_home:uuid/node/1aa48b9e-63be-4e62-a816-aa3a95159c8a'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/1aa48b9e-63be-4e62-a816-aa3a95159c8a',
    'router_path' => 'uuid',
    'link_title' => 'Home',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_home:uuid/node/1aa48b9e-63be-4e62-a816-aa3a95159c8a',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -50,
    'customized' => 0,
  );
  // Exported menu link: main-menu_irrigation-systems:uuid/node/1af48074-38ef-4661-886e-a3ceb1243adf.
  $menu_links['main-menu_irrigation-systems:uuid/node/1af48074-38ef-4661-886e-a3ceb1243adf'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/1af48074-38ef-4661-886e-a3ceb1243adf',
    'router_path' => 'uuid',
    'link_title' => 'Irrigation Systems',
    'options' => array(
      'identifier' => 'main-menu_irrigation-systems:uuid/node/1af48074-38ef-4661-886e-a3ceb1243adf',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'uuid' => '1af48074-38ef-4661-886e-a3ceb1243adf',
    'vuuid' => 'f848bfa8-bdf9-4124-9377-0b670620a852',
    'parent_identifier' => 'main-menu_services:uuid/node/1a3bc130-4909-4119-8127-488df7d11c11',
  );
  // Exported menu link: main-menu_landscaping-home-hero-image:uuid/node/1ab3d96b-ff6e-4423-96bd-43879e1a04ac.
  $menu_links['main-menu_landscaping-home-hero-image:uuid/node/1ab3d96b-ff6e-4423-96bd-43879e1a04ac'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/1ab3d96b-ff6e-4423-96bd-43879e1a04ac',
    'router_path' => 'uuid',
    'link_title' => 'Landscaping Home Hero Image',
    'options' => array(
      'identifier' => 'main-menu_landscaping-home-hero-image:uuid/node/1ab3d96b-ff6e-4423-96bd-43879e1a04ac',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => '1ab3d96b-ff6e-4423-96bd-43879e1a04ac',
    'vuuid' => 'e3ce98eb-fafe-47cf-a214-761b91cf20b9',
    'parent_identifier' => 'main-menu_home:uuid/node/1aa48b9e-63be-4e62-a816-aa3a95159c8a',
  );
  // Exported menu link: main-menu_landscaping-home-hero-video:uuid/node/1adf2c54-04c8-434b-821d-9da39845bc2f.
  $menu_links['main-menu_landscaping-home-hero-video:uuid/node/1adf2c54-04c8-434b-821d-9da39845bc2f'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/1adf2c54-04c8-434b-821d-9da39845bc2f',
    'router_path' => 'uuid',
    'link_title' => 'Landscaping Home Hero Video',
    'options' => array(
      'identifier' => 'main-menu_landscaping-home-hero-video:uuid/node/1adf2c54-04c8-434b-821d-9da39845bc2f',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => '1adf2c54-04c8-434b-821d-9da39845bc2f',
    'vuuid' => '666dff6f-5db5-413d-b587-648f6247b059',
    'parent_identifier' => 'main-menu_home:uuid/node/1aa48b9e-63be-4e62-a816-aa3a95159c8a',
  );
  // Exported menu link: main-menu_landscaping:uuid/node/1a3662ec-f4ed-4846-a5e3-1d6c830405e1.
  $menu_links['main-menu_landscaping:uuid/node/1a3662ec-f4ed-4846-a5e3-1d6c830405e1'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/1a3662ec-f4ed-4846-a5e3-1d6c830405e1',
    'router_path' => 'uuid',
    'link_title' => 'Landscaping',
    'options' => array(
      'identifier' => 'main-menu_landscaping:uuid/node/1a3662ec-f4ed-4846-a5e3-1d6c830405e1',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'uuid' => '1a3662ec-f4ed-4846-a5e3-1d6c830405e1',
    'vuuid' => 'ed2b96d2-5af4-42c3-bdad-d1d3267abf6f',
    'parent_identifier' => 'main-menu_services:uuid/node/1a3bc130-4909-4119-8127-488df7d11c11',
  );
  // Exported menu link: main-menu_lawn-services:uuid/node/1a21d93a-69f3-4ec2-a54f-14100d1de7b2.
  $menu_links['main-menu_lawn-services:uuid/node/1a21d93a-69f3-4ec2-a54f-14100d1de7b2'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/1a21d93a-69f3-4ec2-a54f-14100d1de7b2',
    'router_path' => 'uuid',
    'link_title' => 'Lawn Services',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_lawn-services:uuid/node/1a21d93a-69f3-4ec2-a54f-14100d1de7b2',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'uuid' => '1a21d93a-69f3-4ec2-a54f-14100d1de7b2',
    'vuuid' => '51807c52-85fd-44ca-b5d5-b85192db2395',
    'parent_identifier' => 'main-menu_services:uuid/node/1a3bc130-4909-4119-8127-488df7d11c11',
  );
  // Exported menu link: main-menu_news:blog/modern.
  $menu_links['main-menu_news:blog/modern'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'blog/modern',
    'router_path' => 'blog/modern',
    'link_title' => 'News',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_news:blog/modern',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => -46,
    'customized' => 1,
  );
  // Exported menu link: main-menu_paths-and-roads:uuid/node/1a21a69b-ba7b-458a-839a-f8b9f66bfa6e.
  $menu_links['main-menu_paths-and-roads:uuid/node/1a21a69b-ba7b-458a-839a-f8b9f66bfa6e'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/1a21a69b-ba7b-458a-839a-f8b9f66bfa6e',
    'router_path' => 'uuid',
    'link_title' => 'Paths and Roads',
    'options' => array(
      'identifier' => 'main-menu_paths-and-roads:uuid/node/1a21a69b-ba7b-458a-839a-f8b9f66bfa6e',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'uuid' => '1a21a69b-ba7b-458a-839a-f8b9f66bfa6e',
    'vuuid' => '7dbd8c76-3279-4449-8fcd-993f8c3078d1',
    'parent_identifier' => 'main-menu_services:uuid/node/1a3bc130-4909-4119-8127-488df7d11c11',
  );
  // Exported menu link: main-menu_planting--weed-removal:uuid/node/1acf841c-d599-47ca-b3e7-640c1c4e6615.
  $menu_links['main-menu_planting--weed-removal:uuid/node/1acf841c-d599-47ca-b3e7-640c1c4e6615'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/1acf841c-d599-47ca-b3e7-640c1c4e6615',
    'router_path' => 'uuid',
    'link_title' => 'Planting & Weed Removal',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_planting--weed-removal:uuid/node/1acf841c-d599-47ca-b3e7-640c1c4e6615',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'uuid' => '1acf841c-d599-47ca-b3e7-640c1c4e6615',
    'vuuid' => 'ab2b2b45-9774-4f6a-a0c1-c1c78f466e25',
    'parent_identifier' => 'main-menu_services:uuid/node/1a3bc130-4909-4119-8127-488df7d11c11',
  );
  // Exported menu link: main-menu_projects:gallery.
  $menu_links['main-menu_projects:gallery'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'gallery',
    'router_path' => 'gallery',
    'link_title' => 'Projects',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_projects:gallery',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: main-menu_services:uuid/node/1a3bc130-4909-4119-8127-488df7d11c11.
  $menu_links['main-menu_services:uuid/node/1a3bc130-4909-4119-8127-488df7d11c11'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/1a3bc130-4909-4119-8127-488df7d11c11',
    'router_path' => 'uuid',
    'link_title' => 'Services',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_services:uuid/node/1a3bc130-4909-4119-8127-488df7d11c11',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -47,
    'customized' => 1,
    'uuid' => '1a3bc130-4909-4119-8127-488df7d11c11',
    'vuuid' => '465984d9-729a-4f33-b6b6-4c4fecffdb75',
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('About Us');
  t('Certifications');
  t('Company');
  t('Company History');
  t('Contact Us');
  t('FAQ');
  t('Garden Architecture');
  t('Home');
  t('Irrigation Systems');
  t('Landscaping');
  t('Landscaping Home Hero Image');
  t('Landscaping Home Hero Video');
  t('Lawn Services');
  t('News');
  t('Paths and Roads');
  t('Planting & Weed Removal');
  t('Projects');
  t('Services');

  return $menu_links;
}
